// -*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
//
#ifndef __ARDUCOPTER_CONFIG_H__
#define __ARDUCOPTER_CONFIG_H__
//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
//
// WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
//
//  DO NOT EDIT this file to adjust your configuration.  Create your own
//  APM_Config.h and use APM_Config.h.example as a reference.
//
// WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
///
//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
//
// Default and automatic configuration details.
//
// Notes for maintainers:
//
// - Try to keep this file organised in the same order as APM_Config.h.example
//
#include "defines.h"

//////////////////////////////////////////////////////////////////////////////
// Loiter position control gains
//
#ifndef RATE_ROLL_P
 # define RATE_ROLL_P             		.1f
#endif

#ifndef RATE_ROLL_I
 # define RATE_ROLL_I             		0.0f
#endif

#ifndef RATE_ROLL_D
 # define RATE_ROLL_D          			0
#endif

#ifndef RATE_ROLL_IMAX
 # define RATE_ROLL_IMAX          		500
#endif


#endif // __ARDUCOPTER_CONFIG_H__
